CREATE DATABASE RecapProject
GO;

USE RecapProject;
Go

CREATE TABLE Cars(
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    BrandId INT NOT NULL,
    ColorId INT NOT NULL,
    Name NVARCHAR(50) NOT NULL,
    ModelYear INT NOT NULL,
    DailyPrice  DECIMAL(14,2) NOT NULL,
    Description NVARCHAR(250) NOT NULL
)

CREATE TABLE Colors(
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(25) NOT NULL
)

CREATE TABLE Brands(
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(25) NOT NULL
)


ALTER TABLE Cars
ADD FOREIGN KEY (ColorId) REFERENCES Colors(Id);

ALTER TABLE Cars
ADD FOREIGN KEY (BrandId) REFERENCES Brands(Id);
