CREATE DATABASE RecapProject
GO;

USE RecapProject;
Go

CREATE TABLE Cars
(
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    BrandId INT NOT NULL,
    ColorId INT NOT NULL,
    Name NVARCHAR(50) NOT NULL,
    ModelYear INT NOT NULL,
    DailyPrice DECIMAL(14,2) NOT NULL,
    Description NVARCHAR(250) NOT NULL
)

CREATE TABLE Colors
(
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(25) NOT NULL
)

CREATE TABLE Brands
(
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(25) NOT NULL
)

ALTER TABLE Cars
ADD FOREIGN KEY (ColorId) REFERENCES Colors(Id);

ALTER TABLE Cars
ADD FOREIGN KEY (BrandId) REFERENCES Brands(Id);

CREATE TABLE Users
(
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(25) NOT NULL,
    LastName NVARCHAR(25),
    Email NVARCHAR(50) NOT NULL,
    Password NVARCHAR(50) NOT NULL
)

CREATE TABLE Customers
(
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    UserId INT NOT NULL,
    CompanyName NVARCHAR(100) NOT NULL
)

CREATE TABLE Rentals
(
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    CarId INT NOT NULL,
    CustomerId INT NOT NULL,
    RentDate DATE NOT NULL,
    ReturnDate DATE
)

ALTER TABLE Customers
ADD FOREIGN KEY (UserId)  REFERENCES Users(Id)

ALTER TABLE Rentals
ADD FOREIGN KEY (CarId) REFERENCES Cars(Id)

ALTER TABLE Rentals
ADD FOREIGN KEY (CustomerId) REFERENCES Customers(Id)

